apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-autoscaler-global-config
  namespace: default
data:
  PROMETHEUS_URL: "http://victoriametrics.monitoring.svc.cluster.local:8428/api/v1/query"
  CHECK_INTERVAL_SECONDS: "60"
  RETRAIN_INTERVAL_MINUTES: "1440"  # Daily retraining
  ENABLE_RETRAINING: "true"  # ← New flag here
---  
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-config-adservice
data:
  NAMESPACE: "default"
  TARGET_DEPLOYMENT: "adservice"
  MIN_REPLICAS: "2"
  MAX_REPLICAS: "10"
  SCALING_STEP: "1"
  SEQ_LENGTH: "10"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-config-cartservice
data:
  NAMESPACE: "default"
  TARGET_DEPLOYMENT: "cartservice"
  MIN_REPLICAS: "2"
  MAX_REPLICAS: "10"
  SCALING_STEP: "1"
  SEQ_LENGTH: "10"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-config-currencyservice
data:
  NAMESPACE: "default"
  TARGET_DEPLOYMENT: "currencyservice"
  MIN_REPLICAS: "2"
  MAX_REPLICAS: "10"
  SCALING_STEP: "1"
  SEQ_LENGTH: "10"   
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-config-emailservice
data:
  NAMESPACE: "default"
  TARGET_DEPLOYMENT: "emailservice"
  MIN_REPLICAS: "2"
  MAX_REPLICAS: "10"
  SCALING_STEP: "1"
  SEQ_LENGTH: "10" 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-config-frontend
data:
  NAMESPACE: "default"
  TARGET_DEPLOYMENT: "frontend"
  MIN_REPLICAS: "2"
  MAX_REPLICAS: "10"
  SCALING_STEP: "1"
  SEQ_LENGTH: "10" 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-config-paymentservice
data:
  NAMESPACE: "default"
  TARGET_DEPLOYMENT: "paymentservice"
  MIN_REPLICAS: "2"
  MAX_REPLICAS: "10"
  SCALING_STEP: "1"
  SEQ_LENGTH: "10" 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-config-productcatalogservice
data:
  NAMESPACE: "default"
  TARGET_DEPLOYMENT: "productcatalogservice"
  MIN_REPLICAS: "2"
  MAX_REPLICAS: "10"
  SCALING_STEP: "1"
  SEQ_LENGTH: "10"   
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-config-redis-cart
data:
  NAMESPACE: "default"
  TARGET_DEPLOYMENT: "redis-cart"
  MIN_REPLICAS: "2"
  MAX_REPLICAS: "10"
  SCALING_STEP: "1"
  SEQ_LENGTH: "10"   
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-config-shippingservice
data:
  NAMESPACE: "default"
  TARGET_DEPLOYMENT: "shippingservice"
  MIN_REPLICAS: "2"
  MAX_REPLICAS: "10"
  SCALING_STEP: "1"
  SEQ_LENGTH: "10"   