apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-autoscaler-global-config
  namespace: monitoring
data:
  PROMETHEUS_URL:  "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
  CHECK_INTERVAL_SECONDS: "60"
  RETRAIN_INTERVAL_MINUTES: "1440"  # Daily retraining
  ENABLE_RETRAINING: "false"  # ← New flag here
  LEARNING_DAYS: "10"
  GRAFANA_API_KEY:
  GRAFANA_URL: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
  MODEL_PATH: "../data/models"