apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-autoscaler-global-config
  namespace: monitoring
data:
  PROMETHEUS_PORT: "8428"
  HEALTH_PORT: "8901"
  STEP_SECONDS: "60"
  PROMETHEUS_DOMAIN:  "http://vm-victoria-metrics-single-server.monitoring.svc.cluster.local:"
  CHECK_INTERVAL_SECONDS: "60"
  RETRAIN_INTERVAL_MINUTES: "1440"  # Daily retraining
  ENABLE_RETRAINING: "false"  # ← New flag here
  GRAFANA_API_KEY:
  NAMESPACE: "monitoring"
  LEARNING_DAYS: "7"
  RETRAIN_THRESHOLD: "500"
  RETRAIN_COOLDOWN: "3600"
  MIN_REPLICAS: "2"
  MAX_REPLICAS: "10"
  SCALING_STEP: "1"
  SEQ_LENGTH: "50"
  MODEL_PATH: "../data/models"
  HISTORY_FILE: "../data/models/history.pkl"
  LOG_FILE: "/live_data"

 
