apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-autoscaler
  namespace: monitoring
  labels:
    app: smart-autoscaler
    target: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-autoscaler
      target: development
  template:
    metadata:
      labels:
        app: smart-autoscaler
        target: development
    spec:
      containers:
        - name: autoscaler
          image: gcr.io/cairo-university-457016/autoscaling-controller:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: smart-autoscaler-global-config
          env:
            - name: TARGET_DEPLOYMENT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['target']
          volumeMounts:
            - name: autoscaler-data
              mountPath: /date
      volumes:
        - name: autoscaler-data
          persistentVolumeClaim:
            claimName: autoscaler-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: smart-autoscaler-service
  namespace: monitoring
spec:
  selector:
    app: smart-autoscaler
  ports:
    - protocol: TCP
      port: 8900
      targetPort: 8900
  type: ClusterIP            